version: 1.0.{build}
branches:
  only:
  - master
  - fsharp
clone_depth: 15
install:
- ps: >-
  if ($env:APPVEYOR_REPO_BRANCH -ne "fsharp") {

    choco install cmake

    choco install haskellplatform -version 2014.2.0.0

    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\bin"

    $env:Path += ";${env:ProgramFiles}\Haskell Platform\2014.2.0.0\lib\extralibs\bin"

    cabal update

    cabal install cabal-install

  }
build_script:
- ps: >-
  if ($env:APPVEYOR_REPO_BRANCH -ne "fsharp") {

    nuget restore cs\cs.sln

    msbuild cs\cs.sln /verbosity:minimal /p:Configuration=Debug /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild cs\cs.sln /verbosity:minimal /p:Configuration=Fields /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild cs\cs.sln /verbosity:minimal /p:Configuration=CollectionInterfaces /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  } else {

    nuget restore fsharp\fsharp.sln

    msbuild fsharp\fsharp.sln /verbosity:minimal /p:Configuration=Debug /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  }
test_script:
- ps: >-
  if ($env:APPVEYOR_REPO_BRANCH -ne "fsharp") {

    vstest.console /logger:Appveyor cs\test\core\bin\debug\net40\Properties\Bond.UnitTest.dll cs\test\core\bin\debug\net45\Properties\Bond.UnitTest.dll cs\test\core\bin\debug\net40\Fields\Bond.UnitTest.dll cs\test\core\bin\debug\net45\Fields\Bond.UnitTest.dll cs\test\core\bin\debug\net40\CollectionInterfaces\Bond.UnitTest.dll cs\test\core\bin\debug\net45\CollectionInterfaces\Bond.UnitTest.dll cs\test\internal\bin\debug\net40\Bond.InternalTest.dll cs\test\internal\bin\debug\net45\Bond.InternalTest.dll

  } else {

    vstest.console /logger:Appveyor fsharp\test\TypeProvider\bin\Debug\BondFsharpUnitTest.dll

  }
